import { EurekaZoneInfo } from './eureka';
import southHornMap from './southhorn.png';

// https://xivapi.com/search?indexes=Fate&filters=ID%3E=1717,ID%3C=1742&columns=Description,Name,Url

export const zoneInfoSouthHorn: EurekaZoneInfo = {
  mapImage: southHornMap,
  mapWidth: 2048,
  mapHeight: 2048,
  shortName: 'southhorn',
  hasTracker: false,
  onlyShowInactiveWithExplicitRespawns: true,
  treatNMsAsSkirmishes: true,
  mapToPixelXScalar: 51,
  mapToPixelXConstant: -90,
  mapToPixelYScalar: 50,
  mapToPixelYConstant: -50,
  fieldNotes: [
    {
      id: 8,
      name: {
        en: 'Trade Tortoise',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortName: {
        en: 'Tortoise',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      rarity: 0,
    },
    {
      id: 10,
      name: {
        en: 'Nymian Petalodus',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortName: {
        en: 'Petalodus',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      rarity: 0,
    },
    {
      id: 11,
      name: {
        en: 'Persistent Pots',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortName: {
        en: 'Pots',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      rarity: 0,
    },
    {
      id: 14,
      name: {
        en: 'Mythic Idol',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortName: {
        en: 'Idol',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      rarity: 0,
    },
    {
      id: 16,
      name: {
        en: 'Black Chocobos',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortName: {
        en: 'Chocobos',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      rarity: 0,
    },
    {
      id: 17,
      name: {
        en: 'Crescent Berserker',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortName: {
        en: 'Berserker',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      rarity: 0,
    },
    {
      id: 20,
      name: {
        en: 'Cloister Demon',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortName: {
        en: 'Cloister',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      rarity: 0,
    },
  ],
  nms: {
    roughwaters: {
      label: {
        en: 'Rough Waters',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Waters',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 24.7,
      y: 35,
      fateId: 1962,
    },
    thegoldenguardian: {
      label: {
        en: 'The Golden Guardian',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Guardian',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 28.9,
      y: 31.2,
      fateId: 1963,
    },
    kingofthecrescent: {
      label: {
        en: 'King of the Crescent',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Crescent',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 16.9,
      y: 26.5,
      fateId: 1964,
    },
    thewingedterror: {
      label: {
        en: 'The Winged Terror',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Terror',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 10.5,
      y: 9.5,
      fateId: 1965,
    },
    anunendingduty: {
      label: {
        en: 'An Unending Duty',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Duty',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 17,
      y: 22.1,
      fateId: 1966,
    },
    braindrain: {
      label: {
        en: 'Brain Drain',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Brain',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 20.5,
      y: 15,
      fateId: 1967,
    },
    adelicatebalance: {
      label: {
        en: 'A Delicate Balance',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Balance',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 14,
      y: 34.4,
      fateId: 1968,
    },
    sworntosoil: {
      label: {
        en: 'Sworn to Soil',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Sworn',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 9.7,
      y: 28.1,
      fateId: 1969,
    },
    apryingeye: {
      label: {
        en: 'A Prying Eye',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Eye',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 20,
      y: 32.6,
      fateId: 1970,
    },
    fatalallure: {
      label: {
        en: 'Fatal Allure',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Allure',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 23,
      y: 27,
      fateId: 1971,
    },
    servingdarkness: {
      label: {
        en: 'Serving Darkness',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Darkness',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 29.7,
      y: 21.2,
      fateId: 1972,
    },
    persistentpots: {
      label: {
        en: 'Persistent Pots',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      fieldNotes: 11,
      shortLabel: {
        en: 'Pots',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 25.4,
      y: 17.1,
      bunny: true,
      fateId: 1976,
    },
    pleadingpots: {
      label: {
        en: 'Pleading Pots',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      fieldNotes: 11,
      shortLabel: {
        en: 'Pots',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 11.8,
      y: 32,
      bunny: true,
      fateId: 1977,
    },
/*    theforkedtowerblood: {
      *Seems to pop twice, once when weather changes and when it goes back to normal*
      label: {
        en: 'The Forked Tower: Blood',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: '',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 22.7,
      y: 21.6,
      isCritical: true,
      ceKey: 0,
    },  */
    scourgeofthemind: {
      label: {
        en: 'Scourge of the Mind',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Scourge',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 27.4,
      y: 35.9,
      isCritical: true,
      ceKey: 1,
    },
    theblackregiment: {
      label: {
        en: 'The Black Regiment',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      fieldNotes: 16,
      shortLabel: {
        en: 'Regiment',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 30.5,
      y: 28.6,
      isCritical: true,
      ceKey: 2,
    },
    theunbridled: {
      label: {
        en: 'The Unbridled',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      fieldNotes: 17,
      shortLabel: {
        en: 'Unbridled',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 33.8,
      y: 37.4,
      isCritical: true,
      ceKey: 3,
    },
    crawlingdeath: {
      label: {
        en: 'Crawling Death',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Death',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 35,
      y: 32.1,
      isCritical: true,
      ceKey: 4,
    },
    calamitybound: {
      label: {
        en: 'Calamity Bound',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      fieldNotes: 20,
      shortLabel: {
        en: 'Calamity',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 14.6,
      y: 37.4,
      isCritical: true,
      ceKey: 5,
    },
    trialbyclaw: {
      label: {
        en: 'Trial by Claw',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Claw',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 13.2,
      y: 22.9,
      isCritical: true,
      ceKey: 6,
    },
    fromtimesbygone: {
      label: {
        en: 'From Times Bygone',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      fieldNotes: 14,
      shortLabel: {
        en: 'Bygone',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 5.5,
      y: 26.4,
      isCritical: true,
      ceKey: 7,
    },
    companyofstone: {
      label: {
        en: 'Company of Stone',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Stone',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 35.1,
      y: 16.2,
      isCritical: true,
      ceKey: 8,
    },
    sharkattack: {
      label: {
        en: 'Shark Attack',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      fieldNotes: 10,
      shortLabel: {
        en: 'Shark',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 19.1,
      y: 4.4,
      isCritical: true,
      ceKey: 9,
    },
    onthehunt: {
      label: {
        en: 'On the Hunt',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Hunt',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 34,
      y: 20,
      isCritical: true,
      ceKey: 10,
    },
    withextremeprejudice: {
      label: {
        en: 'With Extreme Prejudice',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Prejudice',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 14.4,
      y: 9.3,
      isCritical: true,
      ceKey: 11,
    },
    noisecomplaint: {
      label: {
        en: 'Noise Complaint',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Complaint',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 30.5,
      y: 14.1,
      isCritical: true,
      ceKey: 12,
    },
    cursedconcern: {
      label: {
        en: 'Cursed Concern',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      fieldNotes: 8,
      shortLabel: {
        en: 'Concern',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 22.9,
      y: 10.6,
      isCritical: true,
      ceKey: 13,
    },
    eternalwatch: {
      label: {
        en: 'Eternal Watch',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Watch',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 38.9,
      y: 25.1,
      isCritical: true,
      ceKey: 14,
    },
    flameofdusk: {
      label: {
        en: 'Flame of Dusk',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      shortLabel: {
        en: 'Dusk',
        de: '',
        fr: '',
        ja: '',
        cn: '',
        ko: '',
      },
      x: 10.1,
      y: 18.3,
      isCritical: true,
      ceKey: 15,
    },
  },
};
